esphome:
  name: sonoff-basic-r4
  friendly_name: Sonoff Basic R4

  name_add_mac_suffix: true

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

packages:
  homeassistant: !include includes/homeassistant_config.yaml

http_request:
  verify_ssl: false

ota:
  - platform: esphome
  - platform: http_request

update:
  - platform: http_request
    id: firmware_update_start
    name: Firmware Update
    source: https://diekruecke.github.io/sonoff-basic-r4/firmware/manifest.json

wifi:
  domain: ".smarthome"
  ap:

web_server:
  version: 3

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - switch.toggle: switch_1

switch:
- platform: gpio
  name: none
  id: switch_1
  pin:
    number: 04
  restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: GPIO6
    inverted: yes