esphome:
  name: sonoff-basic-r4
  friendly_name: Sonoff Basic R4

  name_add_mac_suffix: true

  # platformio_options:
  #   board_build.mcu: esp32c3
  #   board_build.variant: esp32c3

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    # sdkconfig_options:
    #   CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
    #   CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
    #   CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

logger:

api:

http_request:

ota:
  - platform: esphome
  - platform: http_request

update:
  - platform: http_request
    id: firmware_update_start
    name: Firmware Update
    source: https://diekruecke.github.io/sonoff-basic-r4/firmware/manifest.json

wifi:
  ap:

web_server:
  version: 3

captive_portal:

#magic switch mode
external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome_components
    components: [ magic_switch ]
    refresh: 1min

magic_switch:
  pin: 5
  on_switch:
    - switch.toggle: switch_1

esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - switch.toggle: switch_1

switch:
- platform: gpio
  name: Tomada
  id: switch_1
  pin:
    number: 04
  restore_mode: ALWAYS_OFF

status_led:
  pin:
    number: GPIO6
    inverted: yes