esphome:
  name: sonoff-basic-r4
  friendly_name: Sonoff Basic R4
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

http_request:

ota:
  - platform: esphome
  - platform: http_request

update:
  - platform: http_request
    id: firmware_update_start
    name: Firmware Update
    source: https://diekruecke.github.io/sonoff-basic-r4/firmware/sonoff-basic-r4/manifest.json

wifi:
  ap:

captive_portal:
